--- Loading the =rc.fnl= file with lua
-- I want to stress the benefits and trade-offs and explain why I am dong this.
-- The drawback is that starting up awesome will be very slightly slower so
-- slightly that it is not noticeable by me.  The benefit is that I no longer
-- need to make sure to compile my =rc.fnl= file into =rc.lua=.  On a more
-- abstract level it is generally better to have "static" files as much as
-- possible, avoiding files that are dynamically generated and this is because
-- these files always have to be in sync and this adds something else that could
-- go wrong somehow. Whereas, "static" files, you just copy them over and they
-- work. I also did not want to version control the file avoid duplication and
-- the compiled =rc.lua= file is a form of duplication or redundancy because the
-- information in it can be completely derived from the =rc.fnl= file.
---- Set the package path
-- So I am hard-coding the path for now.  I need to figure out a way to
-- generalize this.  Right now this is very dependent on arch as well as the
-- version of lua potentially.
package.path = package.path .. ";/usr/share/lua/5.4/?.lua"
---- Actually install
-- I honestly had no idea how to load this fennel file from lua.  Fortunately, I
-- found out how to do it with the following site:
-- https://fennel-lang.org/setup#embedding-the-fennel-compiler-in-a-lua-application
require("fennel").install().dofile(os.getenv("HOME") .. "/.config/awesome/rc.fnl")
