#+AUTHOR: Luis Henriquez-Perez
#+begin_html
<h1 align="center">dotfiles</h1>
#+end_html
These are my dotfiles.  They are managed with [[chezmoi]].
- *simple as possible*
  Although many linux users go too far with it, there is
  truth to the KISS doctrine of keeping things as simple as possible.
- *easy to setup*
  I want to be able to run just one command or script to set up
  all of my dotfiles.  I have not achieved this yet but I am working on it.
- *well-documented*
  Setting up these dotfiles was hard for me to do.  I want to
  help others reading set up their own dotfiles and to do that.  Also I want to
  remember things that I myself did.
** featured programs
Here I'll talk briefly about some of the programs I choose and why I choose
them.
- For dotfile managemtn I am using git bare repo.  Prior to this I had been
  using [[https://www.chezmoi.io/][chezmoi]] however, I found it a bit too overblown for my needs.  Now I use 
- [[https://awesomewm.org/][awesomewm]] At first I was using stumpwm and I have got to say I do love lisp,
  but stumpwm was a bit slow and in fact the first two weeks I used it it
  crashed at least 5 times.  In any case, awesomewm is
  lightweight it is fast, it is written in a real programming language and it is
  extremely customizable.
- [[https://stumpwm.github.io/][stumpwm]] As I have mentioned I am attracted to customizable applications and
  Particularly ones written in lisp.  In this sense.
- [[https://www.gnu.org/software/emacs/][emacs]] Emacs is my editor (see my [[file:./dot_config/emacs/README.org][dedicated README]])
** designated operating system
I use [[https://archlinux.org/][archlinux]] as my operating system.
** how to initialize dotfiles
