#+AUTHOR: Luis Henriquez-Perez
#+begin_html
<h1 align="center">dotfiles</h1>
#+end_html
These are my dotfiles.  They are managed with [[chezmoi]].
- *100% reproducible* I want to be able to get on a fresh install of archlinx or a
  derivative and install all of my packages.  Eventually, I want to switch to
  [[https://guix.gnu.org/][guix]] or [[https://nixos.org/][nix]] to achieve ultimate reproducability.
- *easy to setup* I want to be able to run just one command or script to set up
  all of my dotfiles.  I have not achieved this yet but I am working on it.
- *well-documented* Setting up these dotfiles was hard for me to do.  I want to
  help others reading set up their own dotfiles and to do that.  Also I want to
  remember things that I myself did.
** featured programs
Here I'll talk briefly about some of the programs I choose and why I choose
them.
- [[https://www.chezmoi.io/][chezmoi]] I have not tried many dotfile mangers extensively, but chezmoi
  looked pretty solid to me.  I have tried [[https://yadm.io/][yadm]] and [[https://www.gnu.org/software/stow/][gnu stow]] for dotfile
  management before.  By solid I mean that it covers several things I wanted in
  dotfiles.
- [[https://awesomewm.org/][awesomewm]] At first I was using stumpwm and I have got to say I do love lisp,
  but stumpwm was a bit slow and in fact the first two weeks I used it it
  crashed at least 5 times (I think the problem).  In any case, awesomewm is
  lightweight it is fast, it is written in a real programming language and it is
  extremely customizable.
- [[https://stumpwm.github.io/][stumpwm]] As I have mentioned I am attracted to customizable applications and
  Particularly ones written in lisp.  In this sense.
- [[https://www.gnu.org/software/emacs/][emacs]] Emacs is my editor (see my [[file:./dot_config/emacs/README.org][dedicated README]])
** designated operating system
I am currently using [[https://archlinux.org/][archlinux]] as my operating system, however I am
considering migrating to [[https://guix.gnu.org/][guix]], maybe with parabola as an intermediate
step.

