#+begin_html
<h1 align="center">dotfiles</h1>
<p align="center">
  <a href="https://github.com/d12frosted/environment/actions?query=workflow%3ACI">
    <img src="https://github.com/d12frosted/environment/workflows/CI/badge.svg" alt="CI Status Badge">
  </a>
  <a href="https://github.com/d12frosted/environment/actions?query=workflow%3AEmacs">
    <img src="https://github.com/d12frosted/environment/workflows/Emacs/badge.svg" alt="Emacs Status Badge">
  </a>
</p>
#+end_html
* dotfiles
These are my dotfiles.  They are managed with [[chezmoi]].
** goals
*** reproducability
I want to be able to get on a fresh install of archlinx or a derivative and
install all of my packages.  Eventually, I want to switch to [[][guix]] or
[[][nix]] to achieve ultimate reproducability.
*** one command setup
I want to be able to run just one command or script to set up all of my
dotfiles.  I have not achieved this yet but I am working on it.
** reasoning behind package choices
** turmoil when choosing dotfiles
** chezmoi
I have not tried many dotfile mangers extensively, but chezmoi looked pretty
solid to me.  I have tried [[https://yadm.io/][yadm]] and [[https://www.gnu.org/software/stow/][gnu stow]] for dotfile management
before.  By solid I mean that it covers several things I wanted in dotfiles.
** featured programs
Here I'll talk briefly about some of the programs I choose and why I choose
them.
*** awesomewm
At first I was using stumpwm and I have got to say I do love lisp, but stumpwm
was a bit slow and in fact the first two weeks I used it it crashed at least 5
times (I think the problem).  In any case, awesomewm is lightweight it is fast,
it is written in a real programming language and it is extremely customizable.
*** stumpwm
As I have mentioned I am attracted to customizable applications and particularly
ones written in lisp.  In this sense.
*** emacs
This is the package I have spent the most time on.
** os - archlinux
I am currently using [[https://archlinux.org/][archlinux]] as my operating system, however I am
considering migrating to [[https://guix.gnu.org/][guix]], maybe with parabola as an intermediate
step.

