;; [[file:snapshots/emacs-logo.png]]

;; This file constitutes my emacs configuration and settings.  When you have a long,
;; non-trivial emacs configuration documentation becomes *extremely* important.
;; * emacs
;; :PROPERTIES:
;; :ID:       20230801T181521.277553
;; :END:
;; Emacs is a lisp interpreter masquerading as a text-editor.
;; ** about
;; :PROPERTIES:
;; :ID:       20230929T111323.550699
;; :END:
;; *** why Emacs?
;; :PROPERTIES:
;; :ID:       20231001T045900.022457
;; :END:
;; *** why I choose an org mode configuration over an elisp one
;; :PROPERTIES:
;; :ID:       20230801T072846.682395
;; :END:
;; Choosing a literate configuration over a standard one was a hard decison.  And to
;; really understand the reasoning I had to migrate back and forth multiple times
;; between the two.  As I see it the main advantage of an elisp configuration is
;; that it is consistent with the way emacs itself organizes its files.

;; An org configuration is highly consistent with its org markup language. You can
;; use org for all of your dotfiles and that means all of your dotfiles will be
;; documented in the same syntax.  Furthermore, you modularize. You get a dotfile
;; manager for free.

;; What tipped the scales for choosing a literate configuration is that I already
;; had lots of commentary and documentation for my code--much more than in normal
;; Emacs configurations; and I used links and emphasis markers extensively.
;; Ultimately, I felt that it was better to go all in with =Org= than to half-ass use
;; it in an elisp configuration.
;; ** base
;; :PROPERTIES:
;; :ID:       20230822T164702.892021
;; :END:
;; The goal behind this headline is to setup Emacs.
;; *** disable garbage collection until I'm done with startup
;; :PROPERTIES:
;; :ID:       20230731T162410.519555
;; :END:
;; This variable controls how often.  Setting it to =most-positive-fixnum=, a very
;; big number, essentially disables garbage collection.  The garbage collection is
;; later reset to a reasonable value.
(setq gc-cons-threshold most-positive-fixnum)
;; *** determine whether emacs is in debug mode
;; :PROPERTIES:
;; :ID:       39197346-c420-4518-b8f8-8ea247d6decb
;; :END:
;; This variable is snatched from [[https://github.com/hlissner/doom-emacs][Doom]].  The point of this variable is to serve as
;; an indicator of whether the current Emacs instance is run for
;; debugging. Normally, when starting Emacs I suppress non-critical errors so as
;; not to interfere with startup; but if I know I'm specifically debugging my
;; configuration using this variable then I might disable the suppression of
;; errors.
(defvar oo-debug-p (or (getenv "DEBUG") init-file-debug)
  "When non-nil print debug messages.
The --debug-init flag and setting the DEBUG envar will enable this at startup.")
;; *** store errors that occur in hooks and advices
;; :PROPERTIES:
;; :ID:       20230907T154338.147014
;; :END:
;; This is influenced by the excellent stackoverflow on
;; [[https://emacs.stackexchange.com/questions/669/how-to-gracefully-handle-errors-in-init-file][how-to-gracefully-handle-errors-in-init-file]].  The idea is that I don't want
;; errors to interfere with startup or with my usage of Emacs.  But I also don't
;; want to ignore them altogether.  Instead, I want to raise them when I decide
;; to I want to deal with them; from the comfort of a working Emacs
;; configuration.
(defvar oo-errors nil
  "An alist of errors that occur in advices or hooks during Emacs startup.
Each element looks like (HOOK-OR-ADVICE . ERROR).  HOOK-OR-ADVICE is a hook or
an advice symbol that raised an error.  ERROR is the error object generated by
HOOK-OR-ADVICE.")
;; *** define a place to store temporary files
;; :PROPERTIES:
;; :ID:       be8993d3-c8f7-451b-8cb4-04a9138e5c4e
;; :END:
;; It's useful to store directories which I reference frequently in variables and
;; functions.  This way I can reference the full path.  Certain directories are
;; important; and I end up referencing them alot.  One of these is my
;; cache directory.
(defvar oo-cache-dir (concat user-emacs-directory "cache/")
  "Directory containing files used for caching information.")
;; *** set the initial font
;; :PROPERTIES:
;; :ID:       20230731T162406.357220
;; :END:
;; It is more performant to do this in the =early-init.el= because that's run
;; when the frame has not yet been initialized.  However, since the frame has
;; not been initialized none of the commands for checking system fonts work yet;
;; meaning that I can't robustly check for existing fonts.  In fact, I have to
;; know that the font I set in the =early-init.el= file is present because if it
;; isn't Emacs will crash due to the frame having a non-existent font.  Although
;; it is less performant, it's better for robustness to set the font here.
(let (font)
  (setq font (or (font-spec :name "Nimbus Mono PS"
			                :weight 'normal
			                :slant 'normal
			                :size 15)
                 (font-spec :name "Iosevka Comfy Wide"
			                :weight 'normal
			                :slant 'normal
			                :size 15)
	             (font-spec :name "SpaceMono Nerd Font"
			                :weight 'normal
			                :slant 'normal
			                :size 15)
		         (font-spec :name "iMWritingMono Nerd Font Mono"
			                :weight 'normal
			                :slant 'normal
			                :size 15)))
  (set-face-attribute 'default nil :font font))

(require 'oo-boostrap-packages)
