;; -*- mode: emacs-lisp; lexical-binding: t; no-byte-compile: t -*-
;; * base
;; :PROPERTIES:
;; :ID:       20230822T164702.892021
;; :END:
;; **  disable garbage collection until I'm done with startup
;; :PROPERTIES:
;; :ID:       20230731T162410.519555
;; :END:
;; This variable controls how often.  Setting it to =most-positive-fixnum=, a very
;; big number, essentially disables garbage collection.  The garbage collection is
;; later reset to a reasonable value.
(setq gc-cons-threshold most-positive-fixnum)
;; **  determine whether emacs is in debug mode
;; :PROPERTIES:
;; :ID:       39197346-c420-4518-b8f8-8ea247d6decb
;; :END:
;; This variable is snatched from [[https://github.com/hlissner/doom-emacs][Doom]].  The point of this variable is to serve as
;; an indicator of whether the current Emacs instance is run for
;; debugging. Normally, when starting Emacs I suppress non-critical errors so as
;; not to interfere with startup; but if I know I'm specifically debugging my
;; configuration using this variable then I might disable the suppression of
;; errors.
(defvar oo-debug-p (or (getenv "DEBUG") init-file-debug)
  "When non-nil print debug messages.
The --debug-init flag and setting the DEBUG envar will enable this at startup.")
;; **  store errors that occur in hooks and advices
;; :PROPERTIES:
;; :ID:       20230907T154338.147014
;; :END:
;; This is influenced by the excellent stackoverflow on
;; [[https://emacs.stackexchange.com/questions/669/how-to-gracefully-handle-errors-in-init-file][how-to-gracefully-handle-errors-in-init-file]].  The idea is that I don't want
;; errors to interfere with startup or with my usage of Emacs.  But I also don't
;; want to ignore them altogether.  Instead, I want to raise them when I decide
;; to I want to deal with them; from the comfort of a working Emacs
;; configuration.
(defvar oo-errors nil
  "An alist of errors that occur in advices or hooks during Emacs startup.
Each element looks like (HOOK-OR-ADVICE . ERROR).  HOOK-OR-ADVICE is a hook or
an advice symbol that raised an error.  ERROR is the error object generated by
HOOK-OR-ADVICE.")
;; **  define a place to store temporary files
;; :PROPERTIES:
;; :ID:       be8993d3-c8f7-451b-8cb4-04a9138e5c4e
;; :END:
;; It's useful to store directories which I reference frequently in variables and
;; functions.  This way I can reference the full path.  Certain directories are
;; important; and I end up referencing them alot.  One of these is my
;; cache directory.
(defvar oo-cache-dir (concat user-emacs-directory "cache/")
  "Directory containing files used for caching information.")
;; * install packages
;; The million dollar question is: how should installing packages work?  For me
;; I'd like to run a script in bash or preferably elisp that just installs my
;; packages for me up front and then at that point I can just run my emacs
;; configuration.  I just want a script that will install packages.
;; In case I want to use different package mangers I want.
(setq load-path (append load-path
                        (eval-when-compile
                          (require 'oo-packages)
                          (oo-install-packages))))

;; (edwina :fetcher gitlab :repo "ajgrf/edwina" :ref "f95c31b" :branch "master")
