;; [[file:snapshots/emacs-logo.png]]
;; Karl Volt argues that =org= has many advantages over =markdown=
;; https://karl-voit.at/2017/09/23/orgmode-as-markup-only/
;; * init.el
;; * boost =gc-cons-threshold=
;; This variable controls how often.  Setting it to =most-positive-fixnum=, a very
;; big number, essentially disables garbage collection.  The garbage collection is
;; later reset to a reasonable value.
(setq gc-cons-threshold most-positive-fixnum)

;; * debugp
;; This variable is snatched from [[https://github.com/hlissner/doom-emacs][Doom]].  The point of this variable is to serve as
;; an indicator of whether the current Emacs instance is run for
;; debugging. Normally, when starting Emacs I suppress non-critical errors so as
;; not to interfere with startup; but if I know I'm specifically debugging my
;; configuration using this variable then I might disable the suppression of
;; errors.
(defvar oo-debug-p (or (getenv "DEBUG") init-file-debug)
  "When non-nil print debug messages.
The --debug-init flag and setting the DEBUG envar will enable this at startup.")

;; * catch any errors in initialization
;; This is influenced by the excellent stackoverflow on
;; [[https://emacs.stackexchange.com/questions/669/how-to-gracefully-handle-errors-in-init-file][how-to-gracefully-handle-errors-in-init-file]].  The idea is that I don't want
;; errors to interfere with startup or with my usage of Emacs.  But I also don't
;; want to ignore them altogether.  Instead, I want to raise them when I decide
;; to I want to deal with them; from the comfort of a working Emacs
;; configuration.
(defvar oo-errors nil
  "An alist of errors that occur in advices or hooks during Emacs startup.
Each element looks like (HOOK-OR-ADVICE . ERROR).  HOOK-OR-ADVICE is a hook or
an advice symbol that raised an error.  ERROR is the error object generated by
HOOK-OR-ADVICE.")

;; It's useful to store directories which I reference frequently in variables and
;; functions.  This way I can reference the full path.  Certain directories are
;; important; and I end up referencing them alot.  One of these is my
;; cache directory.
(defvar oo-cache-dir (concat user-emacs-directory "cache/")
  "Directory containing files used for caching information.")
;; * set the initial font
;; It is more performant to do this in the =early-init.el= because that's run
;; when the frame has not yet been initialized.  However, since the frame has
;; not been initialized none of the commands for checking system fonts work yet;
;; meaning that I can't robustly check for existing fonts.  In fact, I have to
;; know that the font I set in the =early-init.el= file is present because if it
;; isn't Emacs will crash due to the frame having a non-existent font.  Although
;; it is less performant, it's better for robustness to set the font here.
(let (font)
  (setq font (or (font-spec :name "Nimbus Mono PS"
			                :weight 'normal
			                :slant 'normal
			                :size 15)
                 (font-spec :name "Iosevka Comfy Wide"
			                :weight 'normal
			                :slant 'normal
			                :size 15)
	             (font-spec :name "SpaceMono Nerd Font"
			                :weight 'normal
			                :slant 'normal
			                :size 15)
		         (font-spec :name "iMWritingMono Nerd Font Mono"
			                :weight 'normal
			                :slant 'normal
			                :size 15)))
  (set-face-attribute 'default nil :font font))

;; * add lisp directory to load-path
;; The [[][load-path]] is a list of paths that emacs uses to find features it
;; can load.
(push (expand-file-name "lisp" user-emacs-directory) load-path)

;; * =require= the main files
;; This file contains the defaults.  I had been using =el-init= but for just
;; manually load.
(require 'oo-defaults)

;; This file bootstraps `elpaca'.  Still a work in progress.
(require 'oo-bootstrap-elpaca)

;; (require 'oo-base-utils)
(require 'oo-modification-macros)
(require 'oo-block-macro)
;; (require 'oo-bind-functions)

;; * hooks
;; ** prog-mode-hook
;; (oo-add-hook 'prog-mode-hook #'smartparens-strict-mode)
;; (oo-add-hook 'prog-mode-hook #'corfu-mode)
;; (oo-add-hook 'prog-mode-hook #'lispyville-mode)
;; (oo-add-hook 'prog-mode-hook #'flyspell-prog-mode)
;; (oo-add-hook '(prog-mode-hook reb-mode-hook) #'rainbow-delimiters-mode)
;; (oo-add-hook 'prog-mode-hook #'hs-minor-mode)
;; (oo-add-hook 'prog-mode-hook #'auto-fill-mode)

;; ** emacs-startup-hook
;; (oo-add-hook 'emacs-startup-hook #'which-key-mode)
;; ;; (oo-add-hook 'emacs-startup-hook #'idle-require-mode :append t)
;; (oo-add-hook 'emacs-startup-hook #'gcmh-mode :depth 91)
;; (oo-add-hook 'emacs-startup-hook #'recentf-mode)

;; ** on-first-input-hook
;; (oo-add-hook 'on-first-input-hook #'vertico-mode)
;; (oo-add-hook 'on-first-input-hook #'savehist-mode)
;; (oo-add-hook 'on-first-input-hook #'dogears-mode)

;; (oo-add-hook 'vertico-mode-hook #'vertico-buffer-mode)

;; ** after-init-hook
;; (oo-add-hook 'after-init-hook #'require 'evil :depth 10)
;; (oo-add-hook 'after-init-hook #'evil-mode :depth 90)
;; (oo-add-hook 'after-init-hook #'oo-set-window-divider-face :depth 11)
;; (oo-add-hook 'after-init-hook #'window-divider-mode :depth 12)
;; (oo-add-hook 'after-init-hook #'load-theme 'modus-operandi)
;; (oo-add-hook 'after-init-hook #'oo-override-mode :depth -100)

;; ** on-first-file-hook
;; (oo-add-hook 'on-first-file-hook #'save-place-mode)
;; (oo-add-hook 'on-first-file-hook #'super-save-mode)

;; ** emacs-lisp-mode-hook
;; (oo-add-hook 'emacs-lisp-mode-hook 'aggressive-indent-mode)
;; (oo-add-hook 'emacs-lisp-mode-hook #'highlight-quoted-mode)

;; (oo-add-hook 'vertico-mode-hook #'marginalia-mode)
;; (oo-add-hook 'auto-fill-mode-hook #'filladapt-mode)

;; ** text-mode-hook
;; (oo-add-hook '(prog-mode-hook text-mode-hook) #'evil-surround-mode)
;; (oo-add-hook 'text-mode-hook #'flyspell-mode)
;; (oo-add-hook 'text-mode-hook #'auto-fill-mode)
;; (oo-add-hook 'text-mode-hook #'visual-line-mode)
