* emacs
OO emacs is an involved emacs configuration.
* points focus
These are the things I valued as I wrote this configuration.
** performance
When I was desiding how to structure my configuration I thought of the most
performant setup.
** expressive library
** tests
** does it actually improve my productivity?
It is very important to keep this in mind.
* technical details
In general terms, to boost minimize emacs startup you want to load as much of your
configuration as possible with =eval-after-load= (or some variant), minimizing the
lisp code that is evaluated at startup.  You want the bulk of the lisp forms
that are evaluated at startup to be comprised of setting or declaring variables,
defining functions and macros, or setting hooks--all cheap operations.  This in
mind,
** lisp directory structure

The lisp directory has three kinds of files. D= represents an integer from =0= to
=9=.  Emacs loads file in lexigraphical order by default.  I use this naming
system for two things.  One is I want to make sure that I never accidentally use
the name of a built-in feature or a package feature, prefixing my filles with a
two digit number almost guarantees that the name will not be.

- DD-base-NAME
These files are for my emacs setup.  The do not depend on external features
(however, this might change).

- DD-init-FEATURE
Init files are loaded after bases files.  They are loaded during emacs startup
and contains code to setup a package's initialization.  The are "safe" to load
immediately because in general they should only be adding hooks/advices and
setting variables.  They setup =FEATURE= for loading, or customize variables
pertaining to feature, but do not actually load =FEATURE=.

- 99-after-load-FEATURE
There are files that need to be loaded after said feature is loaded.  These
files are not "safe" to load during startup because they rely on
macros/functions/variables from FEATURE.  Evaluation them would either result in
an error for trying to use FEATURE stuff without FEATURE being loaded yet; or it
would inadvertently load FEATURES and perform computations pre-emptively.
** base files
Within the base files there is =01-base-lib= which is loaded second only to
=00-base-variables=.  The file =01-base-lib= cannot have external depencies; it
is a basic library of generic convenience macros and functions I can rely on
before package installation occurs.  However =03=
** naming
*** naming system of advices
*** naming system of hooks
** commentary on process
It is hard to know how to structure things and where to put them.  There are
always benefits and drawbacks to structuring a configuration one way over the
other.  For example, should you put all the keybindings in one file, or should
you segregate them, dividing them by package.  There is no right answer.  It all
depends on whether.  Ultimately, you need to decide one way or the other.
