#!/bin/sh
# Filename: .xinitrc
# Author: Luis Henriquez-Perez <luis@luishp.xyz>
# Created: 2024-12-28 01:16:00
# Description: This file is run automatically when you run `startx`.
# This file was influenced by Luke Smith's voidrice dotfiles.

## xinitrc
# https://wiki.archlinux.org/title/Xinit#xinitrc
# https://wiki.archlinux.org/title/Xorg
### load xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
### set the window manager dynamically
# https://bbs.archlinux.org/viewtopic.php?id=139353
session=${1:-awesome}

case $session in
    qtile             ) exec qtile start;;
    stumpwm           ) exec ~/stumpwm.ros;;
    # https://awesomewm.org/apidoc/documentation/90-FAQ.md.html
    awesome|awesomewm ) exec awesome;;
    i3|i3wm           ) exec i3;;
    kde               ) exec startplasma-x11;;
    xfce|xfce4        ) exec startxfce4;;
    # No known session, try to run it as command
    *                 ) exec $1;;
esac
