#!/bin/sh
# Filename: .xinitrc
# Author: Luis Henriquez-Perez <luis@luishp.xyz>
# Created: 2024-12-28 01:16:00
# Description: This file is run automatically when you run `startx`.
# This file was influenced by Luke Smith's voidrice dotfiles.


# https://wiki.archlinux.org/title/Xinit#xinitrc
# https://wiki.archlinux.org/title/Xorg

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# https://bbs.archlinux.org/viewtopic.php?id=139353
exec awesome
