#!/bin/sh

## xprofile
# https://wiki.archlinux.org/title/Xprofile
### set the wallpaper for the first time
set_wallpaper &
### autostart
# Ensure that I do not start multiple instances of the same process if I log out
# and log back in.
pidof -sx mpd || mpd &
pidof -sx picom || picom &
pidof -sx dunst || dunst &
pidof -sx emacs || emacs --daemon &
### remap caps-lock with escape
setxkbmap -option caps:escape

# I broke my super key on my laptop.  This is temporary code to remap it to the
# left alt key.
if [ "$(cat /etc/hostname)" = "deathscythe" ]; then
    setxkbmap -option altwin:swap_lalt_lwin
fi
