#!/bin/sh
# Filename: xprofile
# Author: Luis Henriquez-Perez <luis@luishp.xyz>
# Created: 2024-12-28 17:04:00
# Description: Run programs & scripts I need for graphical environment.

set_wallpaper &

setxkbmap -option caps:escape

# I broke my super key on my laptop.  This is temporary code to remap it to the
# left alt key.
if [ "$(cat /etc/hostname)" = "deathscythe" ]; then
    setxkbmap -option altwin:swap_lalt_lwin
fi
