#!/usr/bin/env python

# For invoking shell commands.
import subprocess
# For choosing a random wallpaper.
import random
# For getting a list of file paths.
import glob
# For reading and writing the list of wallpapers from and to a file.
import json
# For general file handling stuff.
import os
## setting wallpaper
# What I want is to be able to set the current wallpaper with a random one.  But
# I want to have certain rules for setting the wallpaper.  Specifically, I want
# no wallpaper to be set (n + 1) times before every other wallpaper is set n
# times.  For example, no wallpaper should have been displayed twice before each
# wallpaper is displayed at least once.  The problem I had with this is what
# how does state work when running scripts.

# I am not sure what is going to happen when I quit the cronjob or the window
# manager.  In theory the =used_wallpaper_file= should be reset so that the next
# session my rule is maintained.  +Another idea is I could just write a variable
# to the file called something like ""+.  I think the best idea is to just reset
# I login as a user.

### Specify pertinent directories
wallpaper_dir = os.path.expanduser('~/Pictures/wallpapers/')
used_wallpapers_file = os.path.expanduser('~/.cache/used_wallpapers_file')
### history
# I do not want to set the wallpaper to a /completely/ random wallpaper in my
# wallpaper directory because this would mean that I could just get the same
# wallpaper.  Although unlikely I can get the same wallpaper multiple times.  I
# want it to guarantee it changes when it needs to change (unless I have less
# than 2 wallpapers of course, then I cannot help it).  I also do not want the
# same wallpaper to appear too often.
#### read history
# To keep track of the wallpapers that have been set and the amount of times
# they've been displayed I need to store the data structure in a file.
def read_used_wallpapers (used_wallpapers_file):
    "Read used wallpapers from USED_WALLPAPERS_FILE."
    if not os.path.exists(used_wallpapers_file):
        return []

    with open(used_wallpapers_file, 'r') as file:
        return json.load(file)
#### write history
def write_used_wallpapers (used_wallpapers_file, used_wallpapers):
    "Save used wallpapers from USED_WALLPAPERS_FILE."
    # python does not automatically expand the user according to chatgpt.
    used_wallpapers_file = os.path.expanduser(used_wallpapers_file)
    # ensure the directory for the file exists
    os.makedirs(os.path.dirname(used_wallpapers_file), exist_ok=True)
    with open(used_wallpapers_file, 'w') as file:
        json.dump(used_wallpapers, file)
### create a function that sets the wallpaper
# This function was generated by chatgpt.  And luckily it ended up working.
def set_wallpaper(image_path):
    "Set the wallpaper to path specified by IMAGE_PATH."
    try:
        subprocess.run(["feh", "--bg-scale", image_path], check=True)
        print(f"Wallpaper set to {image_path}")
    except subprocess.CalledProcessError as e:
        print(f"Error setting wallpaper: {e}")
### create a function to choose a random wallpaper
# https://www.geeksforgeeks.org/python-os-listdir-method/
# https://stackoverflow.com/questions/306400/how-can-i-randomly-select-choose-an-item-from-a-list-get-a-random-element
# https://stackoverflow.com/questions/3207219/how-do-i-list-all-files-of-a-directory
# I got my answer from the last stackoverflow post.  There were multiple
# promising answers, but I choose the way using glob because I felt it was the
# shortest one.
def random_wallpaper():
    "Set the wallpaper to a random one."
    # First we get the wallpapers that have already been set.
    used_wallpapers = read_used_wallpapers(used_wallpapers_file)
    # Then we get the list of all the wallpapers
    all_wallpapers = []
    # Damn it, there is certainly a way to do this.  I wish listdir return the
    # list of full path.  This makes more sense to me than just the names.  But
    # whatever.
    for name in os.listdir(wallpaper_dir):
        path = os.path.join(wallpaper_dir, name)
        if os.path.isfile(path):
            all_wallpapers.append(path)
    # If there are no wallpapers at all, do not do anything.
    if not all_wallpapers:
        return None
    # Get the set of wallpapers that haven't been used or more formally the
    # elements of =all_wallpapers= that are not in =used_wallpapers=.
    unused_wallpapers = list(set(all_wallpapers) - set(used_wallpapers))
    #If the list is empty then choose from all the wallpapers.
    # Otherwise, choose from the used wallpapers.
    if unused_wallpapers:
        chosen = random.choice(unused_wallpapers)
    else:
        used_wallpapers = []
        chosen = random.choice(all_wallpapers)
    used_wallpapers.append(chosen)
    write_used_wallpapers(used_wallpapers_file, used_wallpapers)
    return chosen
### set the wallpaper
set_wallpaper(random_wallpaper())
