#!/bin/sh
# Filename: webpage_snapshot
# Author: Luis Henriquez-Perez <luis@luishp.xyz>
# Created: 2025-06-25 15:34:50
# Description: Take a snapshot of the current websti.

# Save current page as single HTML file using monolith
# Usage: qutebrowser will call this with the page URL as $1

URL="$QUTE_URL"

SAVE_DIR="$HOME/Documents/webpage-snapshots"

mkdir -p "$SAVE_DIR"

TITLE="$(echo "$URL" | sed 's#[/:*?"<>|.]#_#g')"

FILENAME="$SAVE_DIR/$TITLE.html"

monolith --no-js --no-fonts --no-css --no-audio "$URL" -o "$FILENAME"

notify-send "qutebrowser" "snapshoted $URL"
