#!/bin/sh
# Filename: webpage_snapshot
# Author: Luis Henriquez-Perez <luis@luishp.xyz>
# Created: 2025-06-25 15:34:50
# Description: Take a snapshot of the current website.

URL="$QUTE_URL"

SAVE_DIR="$HOME/Documents/webpage-snapshots"

mkdir -p "$SAVE_DIR"

TITLE="$(echo "$URL" | sed 's#[/:*?"<>|.]#_#g')"

FILENAME="$SAVE_DIR/$TITLE.html"

# The notification will be immediate (before the snapshot even finish) and the
# snapshot will finish silently.
monolith --no-js --no-fonts --no-css --no-audio "$URL" -o "$FILENAME" &

notify-send "qutebrowser" "snapshoted $URL"
